### ISSUE TITLE
Segmentation fault due to unchecked return when package does not exist

### ISSUE THREAD

**Issue by aiyengar2** [rancher/charts-build-scripts#37]
PR run: https://github.com/rancher/rke2-charts/pull/73/checks?check_run_id=2443701093

```
./bin/charts-build-scripts validate
5
time="2021-04-27T00:44:08Z" level=info msg="Validating against released charts in main"
6
time="2021-04-27T00:44:08Z" level=info msg="Local chart does not need to be prepared"
7
time="2021-04-27T00:44:08Z" level=info msg="Loading dependencies for chart"
8
time="2021-04-27T00:44:08Z" level=info msg="Generated archive: assets/rke2-canal/rke2-canal-v3.13.300-build2021022302-rc00.tgz"
9
time="2021-04-27T00:44:08Z" level=info msg="Generated chart: charts/rke2-canal/rke2-canal/v3.13.300-build2021022302-rc00"
10
time="2021-04-27T00:44:08Z" level=info msg="Local chart does not need to be prepared"
11
time="2021-04-27T00:44:08Z" level=info msg="Loading dependencies for chart"
12
time="2021-04-27T00:44:08Z" level=info msg="Found chart options for cilium in generated-changes/dependencies/cilium/dependency.yaml"
13
time="2021-04-27T00:44:08Z" level=info msg="Found chart options for rke2-cilium-hard-defaults in generated-changes/dependencies/rke2-cilium-hard-defaults/dependency.yaml"
14
panic: runtime error: invalid memory address or nil pointer dereference
15
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1643436]
16

17
goroutine 1 [running]:
18
github.com/rancher/charts-build-scripts/pkg/charts.LocalPackage.Pull(0xc00023b119, 0x6, 0x0, 0x1c03a40, 0xc000323760, 0x1c03a40, 0xc0002cdf60, 0x19ad813, 0x6, 0x0, ...)
19
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/pkg/charts/puller.go:30 +0xb6
20
github.com/rancher/charts-build-scripts/pkg/charts.PrepareDependencies(0x1c03a40, 0xc000323760, 0x1c03a40, 0xc000323a40, 0x19ad813, 0x6, 0x19c148b, 0x11, 0x26d3ee8, 0x0)
21
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/pkg/charts/dependencies.go:75 +0xa44
22
github.com/rancher/charts-build-scripts/pkg/charts.(*Chart).Prepare(0xc000a56e00, 0x1c03a40, 0xc000323760, 0x1c03a40, 0xc000323a40, 0xf, 0x17630e0)
23
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/pkg/charts/chart.go:27 +0xf9
24
github.com/rancher/charts-build-scripts/pkg/charts.(*Package).Prepare(0xc000a56e00, 0x0, 0x0)
25
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/pkg/charts/package.go:39 +0x67
26
github.com/rancher/charts-build-scripts/pkg/charts.(*Package).GenerateCharts(0xc000a56e00, 0x0, 0x0)
27
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/pkg/charts/package.go:95 +0x4f
28
github.com/rancher/charts-build-scripts/pkg/sync.ValidateRepository(0x1c03a40, 0xc0002fde20, 0xc0008b3dd0, 0x2a, 0x0, 0x0, 0xc00081e690, 0x4, 0x1, 0x0, ...)
29
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/pkg/sync/validate.go:52 +0x765
30
main.validateRepo(0xc00032e2c0)
31
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/main.go:248 +0x425
32
github.com/urfave/cli.HandleAction(0x174e660, 0x1a84900, 0xc00032e2c0, 0xc00032e2c0, 0x0)
33
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:526 +0x58
34
github.com/urfave/cli.Command.Run(0x19b2f4d, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a2c1f8, 0x77, 0x0, ...)
35
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x58e
36
github.com/urfave/cli.(*App).Run(0xc000526540, 0xc00000c080, 0x2, 0x2, 0x0, 0x0)
37
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x7e8
38
main.main()
39
	/home/runner/work/rke2-charts/rke2-charts/charts-build-scripts/main.go:121 +0x85a
40
make: *** [Makefile:8: validate] Error 2
```

Probably because we return `nil, nil` here

https://github.com/rancher/charts-build-scripts/blob/0ed30016a86047aa52784701c2b2b68fa857bba2/pkg/charts/parse.go#L71

**Comment by aiyengar2** [comment]
I don't remember the precise reason why, but I remember that this was an issue due to a misconfiguration of the underlying package. Closing out this issue since it is stale, will re-open if the segfault is rediscovered.
